# Generated by Django 5.2.16 on 2026-08-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='auth_id',
            field=models.IntegerField(default=0),
        ),
    ]
